CREATE TABLE client (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 180) PRIMARY KEY ,
  reference_number VARCHAR(64) unique not null ,
  name             VARCHAR(256) not null ,
  current_balance  double not null,
  last_paid        date,
  last_paid_amount double,
  monthly_subscription double,
  address varchar(4000),
  active boolean default true);

CREATE TABLE payment (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 180) PRIMARY KEY ,
  due_month        VARCHAR(64) ,
  due_year         VARCHAR(64) ,
  amount_due       double ,
  total_amount_paid double ,
  imported         boolean ,
  client_id        long not null ,
  foreign key (client_id) references client(id),
  unique (due_month, due_year, client_id)
);

CREATE TABLE transaction (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 180) PRIMARY KEY ,
  on_date          date ,
  due_month        VARCHAR(64) ,
  due_year         VARCHAR(64) ,
  amount_paid      double ,
  imported         boolean ,
  client_id        long not null ,
  foreign key (client_id) references client(id));


CREATE TABLE settings (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 180) PRIMARY KEY ,
  code          varchar(64) unique ,
  value         varchar(64));

